### ISSUE TITLE
gpfs_add_client breaks if client's ssh hostkey changes

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-spectrumscale#10]
If a client server is rebuilt with a new OS, etc. the GPFS master server needs to have the client's hostkey cleared from it's list of known_hosts before the client can be re-added freshly. It seems like this module could clear any references to the client in the known_hosts file relatively easily. There may be other similar cleanup tasks as well.

**Comment by andylytical** [comment]
Can `ssh-keygen -R fqdn.hostname` work?
Probably also should do `ssh-keygen -R ip.addr`
Both above commands could be added to the add_client script.
