### ISSUE TITLE
Add a node to a gpfs nodeclass when joining a cluster

### ISSUE THREAD

**Issue by andylytical** [ncsa/puppet-spectrumscale#27]
Provide a way to specify nodeclass for a node when joining the cluster.

**Comment by andylytical** [comment]
Add class parameter $nodeclasses as an array, can be empty.

In add_client template, add template parameter $nodeclasses

In add_client template, after accept license:, loop through each item in $nodeclasses,
```
<% $nodeclasses.each |$classname| { %> 
$SSHCOMMAND mmchnodeclass <%= $classname %> add -N <%= $client_hostname %>
<% } -%>
```

**Comment by billglick** [comment]
This issue came up again today. This is particularly relevant to VMs running with minimal RAM.

**Comment by jakerundall** [comment]
Elaborating more on the minimal RAM situation, often we add to a special node class to lower the page pool. In those cases, a restart of GPFS (or reboot) or manually lowering the page pool (non-persistently is OK/preferred) is needed. The node class doesn't take care of the page pool immediately; only after future GPFS restarts/node reboots.

**Comment by ckerner** [comment]
It’s really just a timing issue. If you place it in the node class before the daemon is started, then you don’t need to restart. Probably just a tweak to the add node portion.
