### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by jakerundall** [ncsa/puppet-spectrumscale#6]
Here were issues I have seen when rebuilding one node a couple of times. Sorry for lack of analysis.

**Comment by jakerundall** [comment]
First rebuild:

Notice: /Stage[main]/Gpfs::Install/Exec[GPFS-kernel-module]/returns: make World ...
Notice: /Stage[main]/Gpfs::Install/Exec[GPFS-kernel-module]/returns: make InstallImages ...
Notice: /Stage[main]/Gpfs::Install/Exec[GPFS-kernel-module]/returns: ----------------------------------
Notice: /Stage[main]/Gpfs::Install/Exec[GPFS-kernel-module]/returns: mmbuildgpl: Building GPL module co
Notice: /Stage[main]/Gpfs::Install/Exec[GPFS-kernel-module]/returns: ----------------------------------
Notice: /Stage[main]/Gpfs::Install/Exec[GPFS-kernel-module]/returns: executed successfully
Notice: /Stage[main]/Gpfs::Quota/File[/usr/local/bin/myquota]/ensure: defined content as '{md5}01a7effe
Notice: /Stage[main]/Gpfs::Quota/File[/usr/local/bin/mmlsquota]/ensure: created
Notice: /Stage[main]/Gpfs::Quota/File[/usr/local/bin/mmrepquota]/ensure: created
Notice: /Stage[main]/Gpfs::Add_client/File[/root/gpfs_add_client.sh]/ensure: defined content as '{md5}a
Error: Command exceeded timeout
Error: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: change from notrun to 0 failed: Com
Notice: /Stage[main]/Gpfs::Startup/Exec[mmstartup]: Dependency Exec[gpfs_add_client] has failures: true
Warning: /Stage[main]/Gpfs::Startup/Exec[mmstartup]: Skipping because of failed dependencies
Notice: /Stage[main]/Gpfs::Startup/Exec[mmgetstate]: Dependency Exec[gpfs_add_client] has failures: tru
Warning: /Stage[main]/Gpfs::Startup/Exec[mmgetstate]: Skipping because of failed dependencies
Notice: /Stage[main]/Gpfs::Startup/Exec[wait_for_gpfs_mount]: Dependency Exec[gpfs_add_client] has fail
Warning: /Stage[main]/Gpfs::Startup/Exec[wait_for_gpfs_mount]: Skipping because of failed dependencies
Notice: /Stage[main]/Gpfs::Add_client/Exec[rm_gpfs_add_client_sh]: Dependency Exec[gpfs_add_client] has
Warning: /Stage[main]/Gpfs::Add_client/Exec[rm_gpfs_add_client_sh]: Skipping because of failed dependen
Notice: /Stage[main]/Gpfs::Add_client/Ssh_authorized_key[gpfs_master_authorized_key]/ensure: created
Info: Computing checksum on file /root/.ssh/authorized_keys
Notice: /Stage[main]/Gpfs::Add_client/Firewall[100 ssh from gpfs master]/ensure: created
Info: Computing checksum on file /root/.ssh/id_gpfs
Info: /Stage[main]/Gpfs::Add_client/File[/root/.ssh/id_gpfs]: Filebucketed /root/.ssh/id_gpfs to puppet
Notice: /Stage[main]/Gpfs::Add_client/File[/root/.ssh/id_gpfs]/ensure: removed
Info: Class[Gpfs::Add_client]: Unscheduling all events on Class[Gpfs::Add_client]
Notice: /Stage[main]/Slurm::Users/Group[munge]/ensure: created
Notice: /Stage[main]/Slurm::Users/User[munge]/ensure: created

**Comment by jakerundall** [comment]
Second rebuild:
...

Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: 
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmdelnode: Incorrect node lsst-verify-worker47 specified for command.
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmdelnode: No nodes were found that matched the input specification.
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmdelnode: Command failed. Examine previous error messages to determine cause.
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + delete_firewall
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + [[ 1 -gt 0 ]]
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + set -x
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + mod_firewall_helper '-D INPUT'
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + [[ 1 -gt 0 ]]
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + set -x
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + action='-D INPUT'

...

Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: 
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: Fri May 19 08:44:46 CDT 2017: mmaddnode: Processing node lsst-verify-worker47.ncsa.illinois.edu
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: lost connection
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmdsh: Unexpected error from /usr/bin/scp -p /var/mmfs/ssl/stage/genkeyData1 root@lsst-verify-worker47.ncsa.illinois.edu:/var/mmfs/ssl/stage/genkeyData1. Return code: 1
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmaddnode: Unexpected error from checkNewClusterNode lsst-verify-worker47.ncsa.illinois.edu.  Return code: 255
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmaddnode: mmaddnode quitting.  None of the specified nodes are valid.
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmaddnode: Command failed. Examine previous error messages to determine cause.
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + /usr/bin/ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_gpfs lsst-verify00.ncsa.illinois.edu /usr/lpp/mmfs/bin/mmchlicense client --accept -N lsst-verify-worker47
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmchlicense: Incorrect node lsst-verify-worker47 specified for command.
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmchlicense: No nodes were found that matched the input specification.
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: mmchlicense: Command failed. Examine previous error messages to determine cause.
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + /usr/bin/rm -f /root/.ssh/id_gpfs
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: + /usr/bin/rm -f /root/gpfs_add_client.sh
Notice: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]/returns: executed successfully
Info: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]: Scheduling refresh of Exec[rm_gpfs_add_client_sh]
Info: /Stage[main]/Gpfs::Add_client/Exec[gpfs_add_client]: Scheduling refresh of Class[Gpfs::Startup]
Info: Class[Gpfs::Startup]: Scheduling refresh of Exec[mmstartup]
Info: Class[Gpfs::Startup]: Scheduling refresh of Exec[mmgetstate]
Info: Class[Gpfs::Startup]: Scheduling refresh of Exec[wait_for_gpfs_mount]
Notice: /Stage[main]/Gpfs::Startup/Exec[mmstartup]/returns: mmstartup: This node does not belong to a GPFS cluster.
Notice: /Stage[main]/Gpfs::Startup/Exec[mmstartup]/returns: mmstartup: Command failed. Examine previous error messages to determine cause.
Error: mmstartup returned 1 instead of one of [0]
Error: /Stage[main]/Gpfs::Startup/Exec[mmstartup]/returns: change from notrun to 0 failed: mmstartup returned 1 instead of one of [0]
Notice: /Stage[main]/Gpfs::Startup/Exec[mmstartup]/returns: mmstartup: This node does not belong to a GPFS cluster.
Notice: /Stage[main]/Gpfs::Startup/Exec[mmstartup]/returns: mmstartup: Command failed. Examine previous error messages to determine cause.
Error: /Stage[main]/Gpfs::Startup/Exec[mmstartup]: Failed to call refresh: mmstartup returned 1 instead of one of [0]
Error: /Stage[main]/Gpfs::Startup/Exec[mmstartup]: mmstartup returned 1 instead of one of [0]
Notice: /Stage[main]/Gpfs::Startup/Exec[mmgetstate]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Gpfs::Startup/Exec[mmgetstate]: Skipping because of failed dependencies
Info: /Stage[main]/Gpfs::Startup/Exec[mmgetstate]: Unscheduling all events on Exec[mmgetstate]
Notice: /Stage[main]/Gpfs::Startup/Exec[wait_for_gpfs_mount]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Gpfs::Startup/Exec[wait_for_gpfs_mount]: Skipping because of failed dependencies
Info: /Stage[main]/Gpfs::Startup/Exec[wait_for_gpfs_mount]: Unscheduling all events on Exec[wait_for_gpfs_mount]
Notice: /Stage[main]/Gpfs::Add_client/Exec[rm_gpfs_add_client_sh]/returns: executed successfully
Notice: /Stage[main]/Gpfs::Add_client/Exec[rm_gpfs_add_client_sh]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Gpfs::Add_client/Ssh_authorized_key[gpfs_master_authorized_key]/ensure: created
Info: Computing checksum on file /root/.ssh/authorized_keys
Notice: /Stage[main]/Gpfs::Add_client/Firewall[100 ssh from gpfs master]/ensure: created

...

Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/software]/File[/software]/ensure: created
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/software]/File[/gpfs/fs0/software]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/software]/File[/gpfs/fs0/software]: Skipping because of failed dependencies
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/software]/Mount[/software]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/software]/Mount[/software]: Skipping because of failed dependencies
Info: Gpfs::Bindmount[/software]: Unscheduling all events on Gpfs::Bindmount[/software]
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/datasets]/File[/datasets]/ensure: created
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/datasets]/File[/gpfs/fs0/datasets]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/datasets]/File[/gpfs/fs0/datasets]: Skipping because of failed dependencies
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/datasets]/Mount[/datasets]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/datasets]/Mount[/datasets]: Skipping because of failed dependencies
Info: Gpfs::Bindmount[/datasets]: Unscheduling all events on Gpfs::Bindmount[/datasets]
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/home]/File[/gpfs/fs0/home]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/home]/File[/gpfs/fs0/home]: Skipping because of failed dependencies
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/home]/Mount[/home]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/home]/Mount[/home]: Skipping because of failed dependencies
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/project]/File[/project]/ensure: created
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/project]/File[/gpfs/fs0/project]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/project]/File[/gpfs/fs0/project]: Skipping because of failed dependencies
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/project]/Mount[/project]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/project]/Mount[/project]: Skipping because of failed dependencies
Info: Gpfs::Bindmount[/project]: Unscheduling all events on Gpfs::Bindmount[/project]
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/dedicated]/File[/dedicated]/ensure: created
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/dedicated]/File[/gpfs/fs0/dedicated]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/dedicated]/File[/gpfs/fs0/dedicated]: Skipping because of failed dependencies
Notice: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/dedicated]/Mount[/dedicated]: Dependency Exec[mmstartup] has failures: true
Warning: /Stage[main]/Profile::Gpfs_bindmount/Gpfs::Bindmount[/dedicated]/Mount[/dedicated]: Skipping because of failed dependencies
Info: Gpfs::Bindmount[/dedicated]: Unscheduling all events on Gpfs::Bindmount[/dedicated]
Notice: /Stage[main]/Profile::Collectd/Collectd::Plugin::Network::Server[141.142.208.107]/File[/etc/collectd.d/network-server-141.142.208.107.conf]/ensure: defined content as '{md5}0362f3f186c76ed111a0f7f3ebb8a9e5'
Info: /Stage[main]/Profile::Collectd/Collectd::Plugin::Network::Server[141.142.208.107]/File[/etc/collectd.d/network-server-141.142.208.107.conf]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Profile::Collectd/Collectd::Plugin::Network::Server[10.142.181.3]/File[/etc/collectd.d/network-server-10.142.181.3.conf]/ensure: defined content as '{md5}4c6d7f989ce612e6e7cb2fc285b00b70'
Info: /Stage[main]/Profile::Collectd/Collectd::Plugin::Network::Server[10.142.181.3]/File[/etc/collectd.d/network-server-10.142.181.3.conf]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Cpu/Collectd::Plugin[cpu]/File[cpu.load]/ensure: defined content as '{md5}b352507c28e76222fe75455d6a74e5a5'
Info: /Stage[main]/Collectd::Plugin::Cpu/Collectd::Plugin[cpu]/File[cpu.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Df/Collectd::Plugin[df]/File[df.load]/ensure: defined content as '{md5}44d8242263c17cf9dc805f84c80165ca'
Info: /Stage[main]/Collectd::Plugin::Df/Collectd::Plugin[df]/File[df.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]/ensure: defined content as '{md5}98cd4523a355f4ea6a49c381408380e3'
Info: /Stage[main]/Collectd::Plugin::Load/Collectd::Plugin[load]/File[load.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Cpufreq/Collectd::Plugin[cpufreq]/File[cpufreq.load]/ensure: defined content as '{md5}3209f3053017341d7d72bb1a6226b85d'
Info: /Stage[main]/Collectd::Plugin::Cpufreq/Collectd::Plugin[cpufreq]/File[cpufreq.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Disk/Collectd::Plugin[disk]/File[disk.load]/ensure: defined content as '{md5}bcd29dd5e41c48e589831845da1eb648'
Info: /Stage[main]/Collectd::Plugin::Disk/Collectd::Plugin[disk]/File[disk.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Memory/Collectd::Plugin[memory]/File[memory.load]/ensure: defined content as '{md5}e303246961970ca7aaad379146fa0a4f'
Info: /Stage[main]/Collectd::Plugin::Memory/Collectd::Plugin[memory]/File[memory.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[processes.load]/ensure: defined content as '{md5}f56739142fda8aad962dd71f844936ae'
Info: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[processes.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Uptime/Collectd::Plugin[uptime]/File[uptime.load]/ensure: defined content as '{md5}f1c5f9724253693b4ebc055fca8cdfaa'
Info: /Stage[main]/Collectd::Plugin::Uptime/Collectd::Plugin[uptime]/File[uptime.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Users/Collectd::Plugin[users]/File[users.load]/ensure: defined content as '{md5}195b352fbe6775e9171942f52318fc9f'
Info: /Stage[main]/Collectd::Plugin::Users/Collectd::Plugin[users]/File[users.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Plugin::Network/Collectd::Plugin[network]/File[network.load]/ensure: defined content as '{md5}b9e4cf8e9271a9267572ac17e622da39'
Info: /Stage[main]/Collectd::Plugin::Network/Collectd::Plugin[network]/File[network.load]: Scheduling refresh of Service[collectd]
Notice: /Stage[main]/Collectd::Service/Service[collectd]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Collectd::Service/Service[collectd]: Unscheduling refresh on Service[collectd]
Info: Stage[main]: Unscheduling all events on Stage[main]
Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml

...

**Comment by andylytical** [comment]
This looks like "gpfs master server" cannot communicate with client machine.  "Gpfs master server" requires passwordless root access to client.  I've seen this on other machines where other configs needed changes:
- /etc/ssh/sshd_config
```
PermitRootLogin=yes
AllowGroups root
```

- /etc/security/access.conf
```
+ : root : IP-ADDRESS-OF-GPFS-MASTER-SERVER
```

Not entirely sure how to fix or mitigate this.  Two thoughts are:
1. Attempt to enforce these changes
   1. Difficult since there is no standard (puppet) way to manage these files (would like to see this work similarly to iptables)
2. Check first if passwordless root access works from gpfs-master and fail with error message if it doesn't work
   1. This is a better first approach, I think

**Comment by andylytical** [comment]
Haven't seen this in over 12 months. Closing issue as "wont fix".
